apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: development
  labels:
    app: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    protocol: TCP
    port: 8081
