apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: development
  labels:
    name: mongo
    app: study-plan-service
spec:
  containers:
  - image: mongo
    name: mongo
    # command: ["mongod", "--auth"]
    ports:
    - name: mongo
      containerPort: 27017
      hostPort: 27017
    volumeMounts:
      - name: mongo-storage
        mountPath: /data/db
  volumes:
      - name: mongo-storage
        hostPath:
          path: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: development
  labels:
    name: mongo
    app: study-plan-service
spec:
  selector:
    name: mongo
  type: ClusterIP
  ports:
    - name: db
      port: 27017
      targetPort: 27017
      