apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  default.conf: |
      server {
        listen 80;

        location ^~ /api/v1 {
          proxy_pass http://10.104.46.124:8081/v1;
          proxy_set_header   Host $host;
        }

        location ^~ /v1 {
          proxy_pass http://10.104.46.124:8081;
          proxy_set_header   Host $host;

          proxy_redirect default;
        }

        location ^~ /dev {
          proxy_pass http://10.103.250.238:8081;
          proxy_set_header   Host $host;
        }

      }

      server {
        listen 443;

        location ^~ /api/v1 {
          proxy_pass http://10.104.46.124:8081/v1;
          proxy_set_header   Host $host;
        }

        location ^~ /v1 {
          proxy_pass http://10.104.46.124:8081;
          proxy_set_header   Host $host;
        }

        location ^~ /dev {
          proxy_pass http://10.103.250.238:8081;
          proxy_set_header   Host $host;
        }

      }
