kind: Deployment
apiVersion: extensions/v1beta1
metadata: 
  name: nginx
  namespace: nginx
  labels: 
    run: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: nginx
  template: 
    metadata: 
      labels: 
        run: nginx
    spec: 
      containers: 
      - name: nginx
        image: nginx
        resources: 
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
        - containerPort: 443
          protocol: TCP
          name: https
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: 
      schedulerName: "default-scheduler"
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  status: 
  replicas: 1