apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    run: nginx
spec:
  type: LoadBalancer
  externalIPs:
  # - 178.128.121.0
  - 178.128.96.48
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: nginx

    