apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx
data:
  default.conf: |
      server {
        listen 80;

        location ^~ /api/v1 {
          proxy_pass http://10.102.208.86:8081/v1;
        }

      }
